In [5]:
import pandas as pd
df=pd.read_csv(r"diabetes.csv")
print(df)

        id   chol  stab.glu   hdl  ratio      glyhb    location  age  gender  \
0     1000  203.0        82  56.0    3.6   4.310000  Buckingham   46  female
1     1001  165.0        97  24.0    6.9   4.440000  Buckingham   29  female
2     1002  228.0        92  37.0    6.2   4.640000  Buckingham   58  female
3     1003   78.0        93  12.0    6.5   4.630000  Buckingham   67    male
4     1005  249.0        90  28.0    8.9   7.720000  Buckingham   64    male
..     ...    ...       ...   ...    ...        ...         ...  ...     ...
398  41506  296.0       369  46.0    6.4  16.110001      Louisa   53    male
399  41507  284.0        89  54.0    5.3   4.390000      Louisa   51  female
400  41510  194.0       269  38.0    5.1  13.630000      Louisa   29  female
401  41752  199.0        76  52.0    3.8   4.490000      Louisa   41  female
402  41756  159.0        88  79.0    2.0        NaN      Louisa   68  female

     height  weight   frame  bp.1s  bp.1d  bp.2s  bp.2d  waist   hip  time.ppn
0      62.0   121.0  medium  118.0   59.0    NaN    NaN   29.0  38.0     720.0
1      64.0   218.0   large  112.0   68.0    NaN    NaN   46.0  48.0     360.0
2      61.0   256.0   large  190.0   92.0  185.0   92.0   49.0  57.0     180.0
3      67.0   119.0   large  110.0   50.0    NaN    NaN   33.0  38.0     480.0
4      68.0   183.0  medium  138.0   80.0    NaN    NaN   44.0  41.0     300.0
..      ...     ...     ...    ...    ...    ...    ...    ...   ...       ...
398    69.0   173.0  medium  138.0   94.0  130.0   94.0   35.0  39.0     210.0
399    63.0   154.0  medium  140.0  100.0  146.0  102.0   32.0  43.0     180.0
400    69.0   167.0   small  120.0   70.0    NaN    NaN   33.0  40.0      20.0
401    63.0   197.0  medium  120.0   78.0    NaN    NaN   41.0  48.0     255.0
402    64.0   220.0  medium  100.0   72.0    NaN    NaN   49.0  58.0     900.0

[403 rows x 19 columns]

In [17]:
df.head(30)

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0
5,1008,248.0,94,69.0,3.6,4.81,Buckingham,34,male,71.0,190.0,large,132.0,86.0,NaN,NaN,36.0,42.0,195.0
6,1011,195.0,92,41.0,4.8,4.84,Buckingham,30,male,69.0,191.0,medium,161.0,112.0,161.0,112.0,46.0,49.0,720.0
7,1015,227.0,75,44.0,5.2,3.94,Buckingham,37,male,59.0,170.0,medium,NaN,NaN,NaN,NaN,34.0,39.0,1020.0
8,1016,177.0,87,49.0,3.6,4.84,Buckingham,45,male,69.0,166.0,large,160.0,80.0,128.0,86.0,34.0,40.0,300.0
9,1022,263.0,89,40.0,6.6,5.78,Buckingham,55,female,63.0,202.0,small,108.0,72.0,NaN,NaN,45.0,50.0,240.0
10,1024,242.0,82,54.0,4.5,4.77,Louisa,60,female,65.0,156.0,medium,130.0,90.0,130.0,90.0,39.0,45.0,300.0
11,1029,215.0,128,34.0,6.3,4.97,Louisa,38,female,58.0,195.0,medium,102.0,68.0,NaN,NaN,42.0,50.0,90.0
12,1030,238.0,75,36.0,6.6,4.47,Louisa,27,female,60.0,170.0,medium,130.0,80.0,NaN,NaN,35.0,41.0,720.0
13,1031,183.0,79,46.0,4.0,4.59,Louisa,40,female,59.0,165.0,medium,NaN,NaN,NaN,NaN,37.0,43.0,60.0
14,1035,191.0,76,30.0,6.4,4.67,Louisa,36,male,69.0,183.0,medium,100.0,66.0,NaN,NaN,36.0,40.0,225.0
15,1036,213.0,83,47.0,4.5,3.41,Louisa,33,female,65.0,157.0,medium,130.0,90.0,120.0,96.0,37.0,41.0,240.0
16,1037,255.0,78,38.0,6.7,4.33,Louisa,50,female,65.0,183.0,medium,130.0,100.0,NaN,NaN,37.0,43.0,180.0
17,1041,230.0,112,64.0,3.6,4.53,Louisa,20,male,67.0,159.0,medium,100.0,90.0,NaN,NaN,31.0,39.0,1440.0
18,1045,194.0,81,36.0,5.4,5.28,Louisa,36,male,64.0,126.0,medium,110.0,76.0,NaN,NaN,30.0,34.0,120.0
19,1250,196.0,206,41.0,4.8,11.24,Buckingham,62,female,65.0,196.0,large,178.0,90.0,NaN,NaN,46.0,51.0,540.0
20,1252,186.0,97,50.0,3.7,6.49,Buckingham,70,male,67.0,178.0,large,148.0,88.0,148.0,84.0,42.0,41.0,1020.0
21,1253,234.0,65,76.0,3.1,4.67,Buckingham,47,male,67.0,230.0,large,137.0,100.0,149.0,110.0,45.0,46.0,480.0
22,1254,203.0,299,43.0,4.7,12.74,Buckingham,38,female,69.0,288.0,large,136.0,83.0,NaN,NaN,48.0,55.0,240.0
23,1256,281.0,92,41.0,6.9,5.56,Buckingham,66,female,62.0,185.0,large,158.0,88.0,160.0,88.0,48.0,44.0,285.0
24,1271,228.0,66,45.0,5.1,4.61,Buckingham,24,female,61.0,113.0,medium,100.0,70.0,110.0,70.0,33.0,38.0,210.0
25,1277,179.0,80,92.0,1.9,4.18,Buckingham,41,female,72.0,118.0,small,144.0,112.0,NaN,NaN,28.0,36.0,780.0
26,1280,232.0,87,30.0,7.7,5.10,Buckingham,37,male,68.0,252.0,large,140.0,95.0,NaN,NaN,43.0,47.0,420.0
27,1281,NaN,74,NaN,NaN,4.28,Buckingham,48,male,68.0,100.0,small,120.0,85.0,NaN,NaN,27.0,33.0,510.0
28,1282,254.0,84,52.0,4.9,4.52,Buckingham,43,female,62.0,145.0,medium,125.0,70.0,NaN,NaN,31.0,38.0,720.0
29,1285,215.0,72,42.0,5.1,4.37,Louisa,40,male,70.0,189.0,medium,180.0,122.0,170.0,112.0,37.0,39.0,450.0

In [6]:
df.describe()

,id,chol,stab.glu,hdl,ratio,glyhb,age,height,weight,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
count,403.000000,402.000000,403.000000,402.000000,402.000000,390.000000,403.000000,398.000000,402.000000,398.000000,398.000000,141.000000,141.000000,401.000000,401.000000,400.000000
mean,15978.310174,207.845771,106.672457,50.445274,4.521642,5.589769,46.851117,66.020101,177.592040,136.904523,83.321608,152.382979,92.524823,37.900249,43.039900,341.250000
std,11881.122124,44.445557,53.076655,17.262626,1.727886,2.242595,16.312333,3.918515,40.340666,22.741033,13.589227,21.712952,11.555198,5.729313,5.656713,309.540953
min,1000.000000,78.000000,48.000000,12.000000,1.500000,2.680000,19.000000,52.000000,99.000000,90.000000,48.000000,110.000000,60.000000,26.000000,30.000000,5.000000
25%,4792.500000,179.000000,81.000000,38.000000,3.200000,4.380000,34.000000,63.000000,151.000000,121.250000,75.000000,138.000000,84.000000,33.000000,39.000000,90.000000
50%,15766.000000,204.000000,89.000000,46.000000,4.200000,4.840000,45.000000,66.000000,172.500000,136.000000,82.000000,149.000000,92.000000,37.000000,42.000000,240.000000
75%,20336.000000,230.000000,106.000000,59.000000,5.400000,5.600000,60.000000,69.000000,200.000000,146.750000,90.000000,161.000000,100.000000,41.000000,46.000000,517.500000
max,41756.000000,443.000000,385.000000,120.000000,19.299999,16.110001,92.000000,76.000000,325.000000,250.000000,124.000000,238.000000,124.000000,56.000000,64.000000,1560.000000

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        403 non-null    int64
 1   chol      402 non-null    float64
 2   stab.glu  403 non-null    int64
 3   hdl       402 non-null    float64
 4   ratio     402 non-null    float64
 5   glyhb     390 non-null    float64
 6   location  403 non-null    str
 7   age       403 non-null    int64
 8   gender    403 non-null    str
 9   height    398 non-null    float64
 10  weight    402 non-null    float64
 11  frame     391 non-null    str
 12  bp.1s     398 non-null    float64
 13  bp.1d     398 non-null    float64
 14  bp.2s     141 non-null    float64
 15  bp.2d     141 non-null    float64
 16  waist     401 non-null    float64
 17  hip       401 non-null    float64
 18  time.ppn  400 non-null    float64
dtypes: float64(13), int64(3), str(3)
memory usage: 59.9 KB

In [12]:
df.shape

(403, 19)

In [13]:
df.index

RangeIndex(start=0, stop=403, step=1)

In [18]:
df["age"].unique

<bound method Series.unique of 0      46
1      29
2      58
3      67
4      64
       ..
398    53
399    51
400    29
401    41
402    68
Name: age, Length: 403, dtype: int64>

In [19]:
df["age"]==29

0      False
1       True
2      False
3      False
4      False
       ...
398    False
399    False
400     True
401    False
402    False
Name: age, Length: 403, dtype: bool

In [20]:
df["age"]>29

0       True
1      False
2       True
3       True
4       True
       ...
398     True
399     True
400    False
401     True
402     True
Name: age, Length: 403, dtype: bool

In [21]:
df["age"].value_counts()

age
40    16
36    13
41    13
43    13
37    11
      ..
83     1
81     1
69     1
84     1
89     1
Name: count, Length: 68, dtype: int64

In [22]:
df["chol"]>150

0       True
1       True
2       True
3      False
4       True
       ...
398     True
399     True
400     True
401     True
402     True
Name: chol, Length: 403, dtype: bool

In [1]:
!git --version

git version 2.55.0.windows.5

In [2]:
!git init

Initialized empty Git repository in C:/Users/user/Downloads/gowtham/.git/

In [3]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is ACEC-E489

 Directory of C:\Users\user\Downloads\gowtham

08/09/2026  10:50    <DIR>          .
08/09/2026  10:50    <DIR>          ..
08/09/2026  09:26    <DIR>          .ipynb_checkpoints
08/09/2026  09:23            37,065 diabetes.csv
08/09/2026  10:24            45,879 prgm1.ipynb
               2 File(s)         82,944 bytes
               3 Dir(s)  193,247,080,448 bytes free

In [4]:
!git config user.name "Gowtham"

In [5]:
!git config user.email "2025ci_gowthamr_a@nie.ac.in"

In [8]:
!git remote add origin "https://github.com/2025cigowthamra-maker/Dav.git"

In [ ]:
!git add "prgm1.